"""add_thumbnail_media_type

Revision ID: 4142f2fa3f68
Revises: 48dbe3f7d852
Create Date: 2026-03-29 21:43:13.372069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4142f2fa3f68'
down_revision: Union[str, Sequence[str], None] = '48dbe3f7d852'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('thumbnail_path', sa.String(length=1000), nullable=True))
    op.add_column('sessions', sa.Column('media_type', sa.String(length=20), server_default='audio', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'media_type')
    op.drop_column('sessions', 'thumbnail_path')
    # ### end Alembic commands ###
