"""initial schema

Revision ID: 48dbe3f7d852
Revises: 
Create Date: 2026-02-12 09:06:32.668750

"""
from typing import Sequence, Union

from alembic import op
import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '48dbe3f7d852'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('source_url', sa.String(length=2000), nullable=True),
    sa.Column('channel_name', sa.String(length=200), nullable=True),
    sa.Column('broadcast_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('audio_file_path', sa.String(length=1000), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('processing_stage', sa.String(length=50), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2000), nullable=False),
    sa.Column('title', sa.String(length=1000), nullable=False),
    sa.Column('publisher', sa.String(length=500), nullable=False),
    sa.Column('publication_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_tier', sa.String(length=50), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('content_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('archived_snapshot_url', sa.String(length=2000), nullable=True),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('claims',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('normalized_claim', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('time_scope', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('location_scope', sa.String(length=200), nullable=True),
    sa.Column('speaker_label', sa.String(length=200), nullable=True),
    sa.Column('speaker_party', sa.String(length=100), nullable=True),
    sa.Column('speaker_role', sa.String(length=200), nullable=True),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('claim_type', sa.String(length=30), nullable=False),
    sa.Column('claim_worthiness_score', sa.Float(), nullable=False),
    sa.Column('required_evidence_types', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verdict_label', sa.String(length=20), nullable=True),
    sa.Column('verdict_confidence', sa.Float(), nullable=True),
    sa.Column('verdict_rationale_summary', sa.String(length=500), nullable=True),
    sa.Column('verdict_rationale_bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verdict_version', sa.Integer(), nullable=False),
    sa.Column('verdict_model_used', sa.String(length=100), nullable=True),
    sa.Column('verdict_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('what_would_change_verdict', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_session_id'), 'claims', ['session_id'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=50), nullable=False),
    sa.Column('speaker_label', sa.String(length=200), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transcript_segments_session_id'), 'transcript_segments', ['session_id'], unique=False)
    op.create_table('evidence_passages',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('claim_id', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.String(length=50), nullable=False),
    sa.Column('snippet', sa.String(length=2000), nullable=False),
    sa.Column('relevance_to_claim', sa.String(length=30), nullable=False),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('retrieval_method', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_passages_claim_id'), 'evidence_passages', ['claim_id'], unique=False)
    op.create_index(op.f('ix_evidence_passages_source_id'), 'evidence_passages', ['source_id'], unique=False)
    op.create_table('verdict_audit_log',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('claim_id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('verdict_label', sa.String(length=20), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('rationale_summary', sa.String(length=500), nullable=True),
    sa.Column('rationale_bullets', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('prompt_hash', sa.String(length=64), nullable=True),
    sa.Column('evidence_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verdict_audit_log_claim_id'), 'verdict_audit_log', ['claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verdict_audit_log_claim_id'), table_name='verdict_audit_log')
    op.drop_table('verdict_audit_log')
    op.drop_index(op.f('ix_evidence_passages_source_id'), table_name='evidence_passages')
    op.drop_index(op.f('ix_evidence_passages_claim_id'), table_name='evidence_passages')
    op.drop_table('evidence_passages')
    op.drop_index(op.f('ix_transcript_segments_session_id'), table_name='transcript_segments')
    op.drop_table('transcript_segments')
    op.drop_index(op.f('ix_claims_session_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_table('sources')
    op.drop_table('sessions')
    # ### end Alembic commands ###
